apiVersion: v1
kind: Service
metadata:
  name: hackathon-service
  labels:
    app: hackathon-app

spec:
  type: NodePort

  selector:
    app: hackathon-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
