name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Set Image URI
        run: |
          echo "IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}" >> $GITHUB_ENV

      - name: Deploy Latest Image to EKS
        run: |
          kubectl set image deployment/${{ secrets.K8S_DEPLOYMENT_NAME }} \
            ${{ secrets.K8S_CONTAINER_NAME }}=$IMAGE_URI:latest

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/${{ secrets.K8S_DEPLOYMENT_NAME }}

      - name: Rollback if Failed
        if: failure()
        run: |
          kubectl rollout undo deployment/${{ secrets.K8S_DEPLOYMENT_NAME }}
